config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#landing'
  get "dashboard", to: "dashboard#index", as: "dashboard"
  get "about_us", to: "dashboard#about", as: "about"
  get "faq", to: "dashboard#faq", as: "faq"
  get "landing", to: "dashboard#landing", as: "landing"
  get "charts", to: "dashboard#charts", as: "charts"
  resources :bills
  resources :user_bills
  put '/bills_paid/:id', to: 'user_bills#pay_bill', as: 'pay_bill'
  resources :comments
  resources :groups
  post '/groups/:id/invite', to: 'groups#invite', as: 'invite'
  resources :user_groups

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/

    %title Pass The Buck
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    -# %link{:href => "owl-carousel/owl.carousel.css", :rel => "stylesheet"}
    -# %link{:href => "owl-carousel/owl.theme.css", :rel => "stylesheet"}
    -# %script{:src => "owl-carousel/owl.carousel.js"}
  %body
    #wrapper
      %nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
        .buffer-class
        .container-fluid
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              #leave
              %span.sr-only Toggle navigation
            %a.navbar-brand{:href => '#'}
              = link_to image_tag("oval-ptb-logo.png"), root_path, class: "ptb-logo navbar-brand grow"
          / Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.active
              - if user_signed_in?
                %li
                  .white1.navig-link
                    Welcome #{current_user.first_name}
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to 'About us', about_path, class:'white navig-link'
              %li
                = link_to 'FAQ', faq_path, class:'white navig-link'
              - if user_signed_in?
                -# %li
                -#   %a{:href => "#"}
                -#     = link_to 'Edit account info', edit_user_registration_path
                %li
                  = link_to 'Logout', destroy_user_session_path,class:'white navig-link', method: :delete

              - else
                %li
                  = link_to 'Login', new_user_session_path, class:'white navig-link'
                %li
                  = link_to 'Sign up', new_user_registration_path, class:'white navig-link'
      %p.notice= notice
      %p.alert= alert


      = yield